spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  # nacos 配置

  cloud:
    nacos:
      # nacos 服务地址
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        # 注册组
        group: DEFAULT_GROUP
        namespace: dev
